### ISSUE TITLE
Sep 8th 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#32]
# Currency Reference Data Meeting
## Date
Sep 8th 2020 - 10am EST / 3pm BST

## Untracked attendees
- n/a

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [August 18th meeting minutes](https://github.com/finos/secref-data/issues/23) - _meeting minutes were approved_
- [ ] Update on [Cloud Storage solution](https://github.com/finos/open-developer-platform/issues/154)
   - Proposal to consider Git Large File Store: https://git-lfs.github.com/
- [x] Discuss [Project Plan proposal](https://github.com/finos/secref-data/issues/29)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- A decision was made for work stream participants to reach out to the FINOS community to assess interest in joining this work stream, in line with Stage 1 of the [Project Plan proposal](https://github.com/finos/secref-data/issues/29)

## Action Items
- FINOS (@toshaellison and @aitana16) to draft e-mail to be sent out to FINOS community to assess interest in joining this work stream, in line with Stage 1 of the [Project Plan proposal](https://github.com/finos/secref-data/issues/29)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by Vijayesh-Chandel** [comment]
Hi!

**Comment by toshaellison** [comment]
Here

**Comment by RichardWagener365** [comment]
Here

**Comment by saileshpandey** [comment]
Hi

**Comment by rsiddharthan** [comment]
Hi
