### ISSUE TITLE
Sep 15th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#34]
# Security Reference Data Project Meeting
## Date
09 15 2020 - 11am EST / 4pm BST

## Untracked attendees
- Lodovico Gavotti / Refinitiv
- Pascal Lefrancois / Inovestor
- Sagar Ashok Awant / RBC
- Sagar Bora / Nomura

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Approve [Sep 1st meeting minutes](https://github.com/finos/secref-data/issues/28) 
- [ ] [New project name](https://github.com/finos/secref-data/issues/31#issuecomment-684989785). Potential new names discussed at Sep 1st meeting include:
    - Financial asset reference data
    - Asset reference data
    - Master data management
    - Open master data
    - Open financial reference data
- [ ] Update on [Use cases for securities & Issuer ID mapping](https://github.com/finos/secref-data/issues/33) 
- [ ] Project Logo
- [ ] Target milestones through the end of the year (including understanding if there is any existing code that will “seed” the project).
- [ ] Update on response to question 25 of [SEC proposal to amend Rule 13 f)](https://www.sec.gov/rules/proposed/2020/34-89290.pdf). 
- [ ] Review discrepancy between the individuals in the mailing list and on the calendar invite
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [x] Add link to Use Case issue on the README
- [x] Prepare email/content for distribution to promote contribution.
- [x] Provide examples of how FDC3 approached use cases.

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by sbora-nom** [comment]
Here!

**Comment by adamj-codethink** [comment]
o/

**Comment by toshaellison** [comment]
Here

**Comment by RichardWagener365** [comment]
Hi

**Comment by adamj-codethink** [comment]
"Open financial reference data" is nice

**Comment by jin-cheng-zhu** [comment]
Here

**Comment by toshaellison** [comment]
+1  to open financial reference data

**Comment by saileshpandey** [comment]
+1 for "Open financial reference data"

**Comment by sbora-nom** [comment]
+1 Open Financial Reference Data

**Comment by tonimcderment** [comment]
Hi

**Comment by toshaellison** [comment]
Minutes from the meeting:

**Project name change (to reflect expansion)**:
Attendees added their preference for the new name to this issue and to a Doodle poll (https://doodle.com/poll/46uw69zdm9xt9qme). All votes so far have been for Open Financial Reference Data. One additional name proposed was "Financial Reference Data Standards" (FDRS). Record your vote on this issue before the next meeting so that we can make a final decision.

**Use Cases**
The group discussed a couple of different ways to capture, comment on and prioritize use cases. FDC3 was mentioned as one example to check out:
- Guidance: finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/329252905/uc-wg+discussion+materials
- Review process: https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/264732745/uc-wg+use+cases
- Published on microsite: fdc3.finos.org/docs/1.1/use-cases/overview

The group also discussed one specific use case focused on creating a repository of robust historical data which would be valuable for backtesting, e.g. you could track changes in tickers over time to improve analysis. This could potentially be a paid service. General agreement that current scope should focus on "now" but that capturing historic data could be valuable to add at some point.

Suggestion to add a link to the Use Cases issue in the README. (Done)

**Other**
- Agreed that it makes sense to prepare draft materials that can be easily shared by email, LinkedIn, etc. to attract new contributors. This should also include the value proposition; the types of roles that we need to fill; and potentially they type commitment a new contributor could make.
- Agreed we should suggest to individuals who are on the calendar invite but not on the email list that they join the email list so they can engage in group discussion over email.
