### ISSUE TITLE
Sep 29th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#37]
# Security Reference Data Project Meeting
## Date
Sep 29th 2020 - 11am ET
## Untracked attendees
- Vola Parker / Adaptive
- Benjamin Sandler / AQR
- Mark Etherington / Crux Informatics
- Xue Tan / GLEIF
- Sagar Ashok Sawant / RBC
- Toni McDerment / Refinitiv
- Kristin Hochstein / Refinitiv
- Lodo Gavotti / Refinitiv

## Agenda
- [x] Convene & roll call (5mins)
- [ ] Approve [Sep 15th meeting minutes](https://github.com/finos/secref-data/issues/34) - _meeting minutes were not approved as there was a lack of quorum from the Sep 15th meeting participants. This item has been added to the October 13th agenda_
- [ ] Open items from Sep 15th meeting:
    - [x] [New project name](https://github.com/finos/secref-data/issues/31#issuecomment-684989785) - _there is general agreement among group participants to change the project name to Open Financial Reference Data_
    - [x] Update on [Use cases for securities & Issuer ID mapping](https://github.com/finos/secref-data/issues/33) - _discussed use cases include data tickerization and transaction reconciliation flows, and more generally it was suggested that such a solution would ultimately save discussion cycles within organizations_
    - [x] Target milestones through the end of the year (including understanding if there is any existing code that will “seed” the project). - _A key milestone discussed by the group was the definition of what's going to be used as a standard for entity/issuers and securities. PermID was suggested as a potential standard for entity/issuer, and OID was suggested as a potential standard to be used for securities._
    - [x] Define a subset of securities to start the mapping for - _some participants suggested equities as an interesting use case due to their pervasiveness, the challenges associated with equities reference data, and the potential for this use case to demonstrate the value of the mapping solution_
    - [x] Update on response to question 25 of [SEC proposal to amend Rule 13 f)](https://www.sec.gov/rules/proposed/2020/34-89290.pdf). - FINOS submitted a response on the Foundation's behalf, noting that members may be responding to the proposal directly and that the FINOS response may not reflect their views._
    - [x] Update on Discrepancy between individuals in mailing list and calendar invite - _meeting attendees who are not on the project mailing list have been contacted and offered to be added to it_
- [x] Review reachout to community & volunteer roles. Provide feedback on Securities & Issuer ID mapping [deck](https://docs.google.com/presentation/d/18MrJklV1L14enee2Nc8i4mqenNUaItPeLFCUCTwETMQ/edit#slide=id.g80cac07457_0_0) (see pdf [here](https://github.com/finos/secref-data/files/5300273/SecRef_.Securities.Issuer.ID.mapping_.pdf))
- [ ] Kick Off [Phase II of the SecRef project plan](https://github.com/finos/secref-data/issues/25) 
    - [ ] Create detailed execution plan 
    - [ ] Solution design
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Project participants: submit use cases at https://github.com/finos/secref-data/issues/33
- [ ] Sailesh: reach out to community to identify volunteer SMEs interested in joining the project and potential code contributions

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by aitana16** [comment]
hi!

**Comment by toshaellison** [comment]
present

**Comment by rikoe** [comment]
👋

**Comment by RichardWagener365** [comment]
here
