### ISSUE TITLE
Oct 13th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/secref-data#38]
# Security Reference Data Project Meeting
## Date
Oct 13th 2020 - 11am EST / 4pm BST

## Untracked attendees
- JC Zhu / cmgx
- Peter McNally / CUSIP
- Reza Alavi / wipro
- Rich Robinson / Bloomberg
- Toni McDerment / Refinitiv
- Pascal Lefrancois / Inovestor

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [September 15](https://github.com/finos/secref-data/issues/34) and [September 29](https://github.com/finos/secref-data/issues/37) meeting minutes
- [x] Introducing Alex Papaioannou (Nomura), new SecRef project manager - meeting minutes were approved_
- [x] Introducing new joiners & volunteers 
- [x] Review use cases https://github.com/finos/secref-data/issues/33 - participants suggested use cases arounddata ingestion from new providers and duplicates. Participants committed to submitting further use cases at #33 by the next session_
- [x] High level discussion on architecture: review elements needed for the solution (database, existing mappings, ...)
- [ ] Review workflow https://github.com/finos/secref-data/issues/26 
- [ ] [Phase II of the SecRef project plan](https://github.com/finos/secref-data/issues/25) 
    - [ ] Create detailed execution plan 
    - [ ] Solution design
    - [ ] Assign tasks to project participants
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ]  Participating parties to submit use cases at [https://github.com/finos/secref-data/issues/33](https://github.com/finos/secref-data/issues/33)
- [ ] Tosha to set up meeting with Hyperledger, so that the team can review available technologies that could be used in the solution

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by RichardWagener365** [comment]
Here

**Comment by saileshpandey** [comment]
Hi

**Comment by toshaellison** [comment]
Present

**Comment by apapaioannou92** [comment]
Hi

**Comment by aitana16** [comment]
hi
