### ISSUE TITLE
Nov 3rd 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#41]
# Currency Reference Data Meeting
## Date
Nov 3rd 2020 - 10am EST / 3pm BST

## Untracked attendees
- Vijayesh Chandel / Goldman Sachs

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [Oct 20th](https://github.com/finos/secref-data/issues/39) meeting minutes - _meeting minutes were approved_
- [x] Continue Project Plan Stage 2 – Design (Part 1: Model): 
**Tasks: (expected completion by end of Nov)**
     - [x] Design of a standardized agnostic currency ref data model using example data sets, Alloy Studio _-In Progress_ 
     - [x] Initial focus on currency and commodities to formulate design _-The group has taken that into consideration_
     - [ ] Milestone – to agree on the model and submit it for build _-Pending_
     - [ ] Timeline – October 2020 to end of November 2020 (4 sessions) _-Reminder_
- [x] Review ISO [Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data).
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [x] Agreement on the fact that we will be adding the non ISO code
- [x] Currency symbols – we will not include them as of now; we will address their addition in the future in case they are needed
- [x] Agreement about the necessity of a flag for deliverable and non-deliverable currencies
- [x] Agreement about the necessity of description for all the columns of the Curr Ref Data DB

## Action Items
- [ ] Vijay Chandel to check internally how to make publicly available the model he designed in Legend Studio in June, and to set up a meeting with Sailesh and Tosha to review the features
- [ ] Ted Sanborn to put together a draft description for the columns of the Curr Ref DB
- [ ] Ted Sanborn to check whether there's a list of NDFs within ISDA

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by RichardWagener365** [comment]
hi

**Comment by ElaineFraser** [comment]
hi

**Comment by apapaioannou92** [comment]
hi

**Comment by aitana16** [comment]
hi

**Comment by cr20ro20** [comment]
hi from Craig Rowe

**Comment by ElaineFraser** [comment]
Going through the previous minutes (20th Oct), I notice we didn't revisit 'minor units' in this session

**Comment by apapaioannou92** [comment]
Hi Elaine, thanks for your comment. I will make sure to add "minor units" in the discussion points of next meeting's agenda.

Thank you.

**Comment by apapaioannou92** [comment]
> Going through the previous minutes (20th Oct), I notice we didn't revisit 'minor units' in this session

Hi Elaine, thanks for your comment. I will make sure to add "minor units" in the discussion points of next meeting's agenda.

Thank you.

**Comment by ElaineFraser** [comment]
Couple of links on 'non deliverable', that relate the concept to 'offshore': 
https://www.investopedia.com/terms/n/ndf.asp
file://fwlnp004vf/fraela/home/Downloads/wpiea2020179-print-pdf.pdf
