### ISSUE TITLE
Nov 10th 2020 - SecRef Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#42]
# Security Reference Data Project Meeting
## Date
Nov 10th 2020 - 11am EST / 4pm BST

## Untracked attendees
- Lodovico Gavotti / Refinitiv
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Introduce new joiners & volunteers
- [x] Approve [Oct 27th](https://github.com/finos/secref-data/issues/40) meeting minutes - _meeting minutes were approved_
- [ ] Review submitted use cases [#33](https://github.com/finos/secref-data/issues/33) - (use cases around data ingestion from new providers and duplicates had been scheduled to be submitted by Oct 27th, 2020)
- [ ] Review workflow [#26](https://github.com/finos/secref-data/issues/26)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Confirmed that access to the mapping tool/data will be via API calls and that a GUI is a secondary priority.
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] @toshaellison to add the use cases discussed during the call to [https://github.com/finos/secref-data/issues/33](https://github.com/finos/secref-data/issues/33)
- [ ] Discuss how new data sources will be mapped into the tool.
- [ ] Discuss the process by which licenses can be validated when API calls are made.

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf43ec72e7ce8e771da12093c940c7ab9)
- Meeting Number: 668 805 739
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 668 805 739
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by toshaellison** [comment]
Here

**Comment by TLATER** [comment]
o/

**Comment by rcr203** [comment]
here

**Comment by RichardWagener365** [comment]
hi

**Comment by apapaioannou92** [comment]
hi
