### ISSUE TITLE
Nov 17th 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#43]
# Currency Reference Data Meeting
## Date
Nov 17th 2020 - 10am EST / 3pm BST

## Untracked attendees
- Craig Rowe / cr20ro20 
- Cantor Fitzgerald / cr20ro20 
- Richard Wagener / Codethink / RichardWagener365

## Agenda
- [x] Convene & roll call (5mins)
- [x] Introduce new joiners & volunteers
- [x] Approve [Nov 3rd](https://github.com/finos/secref-data/issues/41) meeting minutes - _meeting minutes were approved_
- [x] Revisit "Minor Units"
- [x] Continue Project Plan Stage 2 – Design (Part 1: Model): 
**Tasks: (expected completion by end of Nov)**
     - [x] Design of a standardized agnostic currency ref data model using example data sets, Alloy Studio _-Completed_ 
     - [x] Initial focus on currency and commodities to formulate design _-The group has taken that into consideration_
     - [ ] Milestone – to agree on the model and submit it for build _-Pending_
     - [ ] Timeline – October 2020 to end of November 2020 (4 sessions) _-Reminder_
- [ ] Review ISO [Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data).
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- In our next meeting on Dec 1st, we will be discussing: 
       a) the group's next steps on the project overall
       b) the design-implementation stage of the project.
- Decision 2
- ...

## Action Items
- [ ] Aitana to connect Vijay and the group with the ISO group
- [ ] Vijay Chandel to check internally how to make publicly available the model he designed in Legend Studio in June, and to set up a meeting with Sailesh to review the features
- [x] Alex/Aitaina to follow up with Ted about the two pending action items from the previous meeting: 
      a) Ted Sanborn to put together a draft description for the columns of the Curr Ref DB
      b) Ted Sanborn to check whether there's a list of NDFs within ISDA

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by Vijayesh-Chandel** [comment]
@apapaioannou92 - as part of the Design section of today's agenda, would like to share with the group the model we have drafted in Alloy Studio so far.

**Comment by ElaineFraser** [comment]
hi

**Comment by aitana16** [comment]
here

**Comment by saileshpandey** [comment]
Hi

**Comment by apapaioannou92** [comment]
hi

**Comment by apapaioannou92** [comment]
> @apapaioannou92 - as part of the Design section of today's agenda, would like to share with the group the model we have drafted in Legend Studio so far. 

@Vijayesh-Chandel please let me know if you are referring to the following model and if this is its most updated version:
[https://legend.finos.org/studio/review/UAT-33/18](https://legend.finos.org/studio/review/UAT-33/18)

Please note that this link is only available to those users who have been set up with read or write access in the Legend Studio instance.

Anyone can request an account on the Legend Studio instance [here ](https://www.finos.org/legend)-- in order to submit edits/ changes to the model users will need to have a CLA in place with FINOS, otherwise FINOS will only be able to give them read access.

Thank you

**Comment by Vijayesh-Chandel** [comment]
@apapaioannou92 the model presented today is currently in my personal workspace, so not yet visible to the group. Once submitted, approved and merged (hoping to have done so this week), it will be fully available, following which further changes can be made as the group requires.  

The model in the above link is the old mock up draft we had made in the summer to help present the concept. This can be kept for reference, but the new model would be the main one for the group to build upon.

**Comment by apapaioannou92** [comment]
> @apapaioannou92 the model presented today is currently in my personal workspace, so not yet visible to the group. Once submitted, approved and merged (hoping to have done so this week), it will be fully available, following which further changes can be made as the group requires.
> 
> The model in the above link is the old mock up draft we had made in the summer to help present the concept. This can be kept for reference, but the new model would be the main one for the group to build upon.

@Vijayesh-Chandel Thank you, please keep us posted when the new version of the model becomes available. We will keep the model posted above for reference purposes.

Thank you.

**Comment by toshaellison** [comment]
I was there
